spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kosty-db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    mvc:
      view:
        prefix: /resources/templates/
        suffix: .ftlh
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false